- hosts: all
  become: yes
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install gpg for apt-key
      apt:
        name: gpg
        state: present

    - name: Add Docker gpg key for apt
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: add Docker's APT repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable
        state: present
        filename: 'docker'

    - name: install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Install Python3 pip
      apt:
        name: python3-pip
        state: present

    - name: Add Docker Python SDK
      shell: pip install docker

    - name: Run whoami without become.
      command: whoami
      changed_when: false
      become: false
      register: whoami

    - name: Set a fact with the user name.
      set_fact:
        login_user: '{{ whoami.stdout }}'

    - name: Add the current user to 'docker' group
      become: yes
      user:
        name: '{{ whoami.stdout }}'
        groups: docker
        append: yes

    - name: Reset SSH connection to refresh user groups
      meta: reset_connection
