- hosts: main

  tasks:
    - name: Copy plone dir
      synchronize:
        src: .
        dest: .

    - name: Add traefik label for main node
      shell: 'docker node update --label-add plone.db.volume=true {{ plone_db_volume_node }}'

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: '{{ plone_db_volume_path }}'
        state: directory
        mode: '0755'
        owner: '999'
        group: '999'

    - name: Deploy Plone stack
      shell: 'docker stack deploy -c plone/docker-compose.yml plone'
      environment:
        - PLONE_ZMI_DOMAIN: '{{ plone_zmi_domain }}'
        - PLONE_CMS_CLASSIC_DOMAIN: '{{ plone_cms_classic_domain }}'
        - PLONE_DB_VOLUME_NODE: '{{ plone_db_volume_node }}'
        - PLONE_DB_VOLUME_PATH: '{{ plone_db_volume_path }}'
        - PLONE_REPLICAS: '{{ plone_replicas }}'
      args:
        chdir: $HOME
